/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AcademicJourneyRouteImport } from './routes/academic-journey'
import { Route as IndexRouteImport } from './routes/index'

const AcademicJourneyRoute = AcademicJourneyRouteImport.update({
  id: '/academic-journey',
  path: '/academic-journey',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-journey': typeof AcademicJourneyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-journey': typeof AcademicJourneyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic-journey': typeof AcademicJourneyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/academic-journey'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/academic-journey'
  id: '__root__' | '/' | '/academic-journey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicJourneyRoute: typeof AcademicJourneyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/academic-journey': {
      id: '/academic-journey'
      path: '/academic-journey'
      fullPath: '/academic-journey'
      preLoaderRoute: typeof AcademicJourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicJourneyRoute: AcademicJourneyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
